### ISSUE TITLE
Germany shouldn't be able to deny the Quisling puppet 

### ISSUE THREAD

**Issue by luceSPT** [SPT-Mod-Dev/SPT-Mod-Dev#118]
or something. They rise up anyway.

**Comment by chaffordh** [comment]
can you point me to what event this is? does it trigger when germany invades norway

**Comment by luceSPT** [comment]
Unfortunately it's in an unimported file, I think.

events\AAT_Norway.txt
Line 2904 "Nor way Jose"

**Comment by chaffordh** [comment]
fixed by allowing germany to select whether norway pursues quisling or rk path
