### ISSUE TITLE
Denmark 1.1

### ISSUE THREAD

**Issue by luceSPT** [SPT-Mod-Dev/SPT-Mod-Dev#138]
- Tutorial tips to explain to folks without AAT the general flow of Denmark gameplay and some tips (can build fascist support early, potential support from Germany, etc.)
- Relax conditions on some of the occupation events, such as installing a collaborationist leader

Not considering fascist-route Denmark at this time. Denmark is already potentially quite efficient, and being able to deploy similar strength on Africa instead of Barb may be imbalanced

**Comment by chaffordh** [comment]
Think Luce worked on this, consider closing

**Comment by luceSPT** [comment]
Close when the PR is in I guess
might come back with a tweak or two before then
