### ISSUE TITLE
Fear and Loathing in Denmark

### ISSUE THREAD

**Issue by luceSPT** [SPT-Mod-Dev/SPT-Mod-Dev#216]
- "Seize Power" didn't change Danish leaders for some reason
- Double check Iceland and Greenland are still available for allied seizure when it goes alt-right

**Comment by luceSPT** [comment]
This is done except for iceland - operation fork is a bit low priority. and less trolly for the Americas. will see

**Comment by luceSPT** [comment]
okay maybe faroes

**Comment by chaffordh** [comment]
create a new issue if required?
