### ISSUE TITLE
This SouthForTahiti guy isnt pulling his weight

### ISSUE THREAD

**Issue by SouthForTahiti** [SPT-Mod-Dev/SPT-Mod-Dev#77]
he was supposed to finish the brazil tree really quickly but its been 9 months since hes done anything

**Comment by SouthForTahiti** [comment]
also im gonna lurk and work on my brazil masterpiece, i will not rat ginger out to the cheyneypolice

**Comment by Stickmiin** [comment]
working as intended, closed
