### ISSUE TITLE
Election Events

### ISSUE THREAD

**Issue by chaffordh** [SPT-Mod-Dev/SPT-Mod-Dev#91]
Consider making democratic election events more predictable or obvious.

**Comment by luceSPT** [comment]
Rigging the elections in favor of partial mob seems to have some support

**Comment by luceSPT** [comment]
Didn't go as far as rigging partial mob, but France now has a third option when Public Opposes Rearmament to do nothing. Will keep issue open for further feedback.

**Comment by chaffordh** [comment]
@luceSPT can this be closed
