### ISSUE TITLE
Add California Girls sung by AI Harry Truman when FDR dies, as requested by Cheyney

### ISSUE THREAD

**Issue by Stickmiin** [SPT-Mod-Dev/SPT-Mod-Dev#95]
he's on something, dunno what

**Comment by Lodomir464** [comment]
Real

śr., 24 kwi 2024, 02:05 użytkownik chaffordh ***@***.***>
napisał:

**Comment by chaffordh** [comment]
@Lodomir464 how is this coming along

**Comment by Lodomir464** [comment]
What

niedz., 21 lip 2024, 04:30 użytkownik chaffordh ***@***.***>
napisał:

**Comment by chaffordh** [comment]
failure
